version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tailadmin-laravel-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    working_dir: /var/www/html

volumes:
  node-modules: