name: Deploy Laravel App

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

                docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

                docker stop tailadmin-app || true
                docker rm tailadmin-app || true

                docker run -d \
                    --name tailadmin-app \
                    -p 800:800 \
                    --restart unless-stopped \
                    -e APP_ENV=production \
                    -e APP_DEBUG=false \
                    -e APP_URL=http://${{ secrets.EC2_HOST }}:8000 \
                    -e APP_KEY=${{ secrets.APP_KEY }} \
                    -e DB_CONNECTION=mysql \
                    -e DB_HOST=${{ secrets.RDS_ENDPOINT }} \
                    -e DB_PORT=3306 \
                    -e DB_DATABASE=tailadmin_laravel \
                    -e DB_USERNAME=laravel \
                    -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
                    ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
                
                docker exec tailadmin-app php artisan migrate --force